name: Pest workflow

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Trust repo for Git
      run: git config --global --add safe.directory /app

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: sockets, gmp
        tools: composer

    - name: Check PHP extensions
      run: php -m

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run Pest tests
      run: ./vendor/bin/pest
