name: Pest workflow

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Trust repo for Git
      run: git config --global --add safe.directory /app

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: sockets, gmp

    - uses: php-actions/composer@v6

    - uses: NWBY/pest-action@v1.2.0
