name: Pest workflow

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: php-actions/composer@v6
    - uses: NWBY/pest-action@v1.2.0
